### ISSUE TITLE
Possibility to add Versioneye Organisation as option

### ISSUE THREAD

**Issue by SenseException** [miyajan/versioneye-slack#17]
In a Test with the console variant of versioneye-slack, the following code is run when I want to get the project information:

``` javascript
postProjectSummary(projectName) {
        return this._versioneye.projects.list().then(json => {
            const project = json.find(project => project['name'] === projectName);
```

An API request for a project list is done and on the json response of the API, it tries to find a project with the given project name.

In my case, I get an empty list by the API because `GET /v2/projects` needs the organisation to return the expected project. The commandline doesn't offer an option to add the organisation.

There should be a option `--orga-name` to put the organisation to the `list()` method to be able to access projects of the organisation.

If I get an okay for this feature, I would like to create a PR for that.

**Comment by miyajan** [comment]
@SenseException Thank you for your reporting! I understood that the ```orga_name``` is required when ```GET /v2/projects``` is called with a personal API key.

Fixed in https://github.com/miyajan/versioneye-slack/pull/18 and v0.3.0 has been released. Thanks! 👍
